# Generated by Django 4.0.5 on 2023-04-10 17:10

from django.db import migrations, models


def set_default_false(apps, schema_editor):
    Comment = apps.get_model('posts', 'Comment')
    Comment.objects.all().update(published=False)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_set_default_false'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_responded',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
    ]
